name: ML PRACTICE CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run test
      run: docker run --rm -v $(pwd):/data cytopia/black . --check --verbose --diff --color

  probability_distribution_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run test
      run: bash test.sh probability_distribution

  draw_beta_distribution_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run test
      run: bash test.sh draw_beta_distribution

  draw_binomial_distribution_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run test
      run: bash test.sh draw_binomial_distribution

  draw_dirichlet_distribution_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run test
      run: bash test.sh draw_dirichlet_distribution

  draw_gaussian_distribution_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run test
      run: bash test.sh draw_gaussian_distribution

  linear_regression_model_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run test
      run: bash test.sh linear_regression_model

  linear_discriminative_model_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run test
      run: bash test.sh linear_discriminative_model

  mixture_density_network_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run test
      run: bash test.sh mixture_density_network

  kernel_method_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run test
      run: bash test.sh kernel_method

  kernel_machine_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run test
      run: bash test.sh kernel_machine

  graphical_model_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run test
      run: bash test.sh graphical_model

  mixed_models_and_EM_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run test
      run: bash test.sh mixed_models_and_EM
